baseurl = "/"
title = "Hunches & Crunches"
author = "Erik Andreasson"
copyright = "Copyright © 2008–2018, Erik Andreasson"
canonifyurls = true
paginate = 3
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
theme = "hugo-blog-jeffprod"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[taxonomies]
    tag = "tags"
    archive = "archives"
[params]
    description = "A practical blog going to the bottom of things within the world of Data Science. Mostly R."
